# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Sparse logistic with lasso penalizer
#' @description Fits a sparse logistic model with lasso penalizer
#' @export
sparse_logit <- function(beta0, Xt, y, lambda = 0.0, maxepochs = 1L, step_scale = 2.0, tol = 1e-3, discount = 0.95) {
    .Call(`_sparselogit_sparse_logit`, beta0, Xt, y, lambda, maxepochs, step_scale, tol, discount)
}

